---
title: "STA 523 Final Project Write Up"
author: "Jie Sun, Leonardo Shu, Shijia Bian, Yang Sun, Ziyue Zeng"
date: "December 12, 2015"
output: html_document
---

The goal of our final project is a text mining for the twitter.

## List of Files for the Final Project 

`load_packages.R`


## Stage I: Load the Package

Before the anaysis, you need load the packages that are in the file `load_packages.R`.

```{r}
## Now we load the packages
EnsurePackage<-function(x)
{x <- as.character(x)
if (!require(x,character.only=TRUE))
{
  install.packages(pkgs=x,repos="http://cran.r-project.org")
  require(x,character.only=TRUE)
}
}

#Identifying packages required 
PrepareTwitter<-function()
{
  EnsurePackage("httr")
  EnsurePackage("devtools")
  EnsurePackage("twitteR")
  EnsurePackage("base64enc")
  EnsurePackage("stringr")
  EnsurePackage("ROAuth")
  EnsurePackage("RCurl")
  EnsurePackage("ggplot2")
  EnsurePackage("tm")
  EnsurePackage("RJSONIO")
  EnsurePackage("wordcloud")
  EnsurePackage("ggplot2") 
  EnsurePackage("streamR")
  EnsurePackage("NYU160J")
  EnsurePackage("grid")
}

PrepareTwitter()
```

## Cluster Analysis

Based on the data we collected, we use cluster analysis to divide them into several groups. The method we use is Ward's Method. This method start out with all sample units in n clusters of size 1 each. In the first step of the algorithm, n - 1 clusters are formed, one of size two and the remaining of size 1. The error sum of squares and r2 values are then computed. The pair of sample units that yield the smallest error sum of squares,  will form the first cluster. Then, in the second step of the algorithm, n - 2 clusters are formed from that n - 1 clusters defined in step 2. These may include two clusters of size 2, or a single cluster of size 3 including the two items clustered in step 1. Again, the value of r2 is maximized. Thus, at each step of the algorithm clusters or observations are combined in such a way as to minimize the results of error from the squares or alternatively maximize the r2 value. The algorithm stops when all sample units are combined into a single large cluster of size n .

In our apps, we let the user choose the cluster number and their interested topics. By running our clustering algorithm, the user is able to see the most relavent words regarding the topic s/he choosed before. What's more, the user is able to see how these words being clustered into k categories according to their distance.Words in red rectangular lines are clustered into one group which implies these words share the most closest distance comparing with other word groups. 